In [1]:
import numpy as np
import pandas as pd

In [2]:
Team1_bat = pd.read_csv("./data/Pak-batting.csv")
Team2_bat = pd.read_csv("./data/Afg-batting.csv")

In [3]:
Team1_bowl = pd.read_csv("./data/Pak-bowling.csv")
Team2_bowl = pd.read_csv("./data/Afg-bowling.csv")

In [4]:
Team1_bat

,Player,Matches,Innings,No,Runs,HS,Avg,BF,SR,100,200,50,4s,6s
0,Fakhar Zaman,37,37,4,1664,210,50.42,359,98.52,4,1,10,192,28
1,Imam-ul-Haq,29,29,5,1389,151,57.88,1711,81.18,6,0,5,103,14
2,Babaz Azam,65,63,9,2761,125,51.13,3219,85.77,9,0,12,231,25
3,Asif Ali,16,12,1,342,52,31.09,261,131.03,0,0,3,20,20
4,Shaheen Afridi,14,6,4,41,19,20.50,58,70.69,0,0,0,2,2
5,Hasan Ali,50,27,8,238,59,12.53,227,104.85,0,0,2,15,13
6,Wahaz Riaz,80,57,13,607,54,13.80,726,83.61,0,0,2,47,23
7,Mohammad Hasnain,5,2,0,28,28,14.00,18,155.56,0,0,0,4,1
8,Mohammad Amir,52,28,10,355,73,19.72,436,81.42,0,0,2,31,8
9,Shadab Khan,35,17,6,294,54,26.73,453,64.90,0,0,3,16,4
10,Shoaib Malik,284,255,40,7526,143,35.00,9188,81.91,9,0,44,603,113
11,Mohammad Hafeez,211,209,15,6377,140,32.87,8373,76.16,11,0,37,644,105
12,Imad Wasim,47,34,14,779,63,38.95,726,107.30,0,0,5,68,16
13,Haris Sohail,35,34,5,1328,130,45.79,1598,83.10,2,0,10,108,18
14,Sarfaraz Ahmed,107,81,19,2136,105,34.45,2425,88.08,2,0,10,163,12

In [42]:
batting_scores = []
for i in range(Team1_bat.shape[0]):
    u = np.sqrt(Team1_bat.iloc[i]['Matches']/Team1_bat.iloc[i]["Innings"])
    v = 20*Team1_bat.iloc[i]["200"]+10*Team1_bat.iloc[i]["100"]+5*Team1_bat.iloc[i]["50"]
    w = 0.3 * v + 0.7 * Team1_bat.iloc[i]["Avg"]
    y = Team1_bat.iloc[i]["SR"]
#     x = 0.2 * (Team1_bat.iloc[i]["Innings"]/Team1_bat.iloc[i]["4s"] + Team1_bat.iloc[i]["Innings"]/Team1_bat.iloc[i]["6s"])
#     if np.isinf(x):
#         career_score = u*w*y
#     else:
#         career_score = u*w*y*x
    career_score = u*w*y
    batting_scores.append(career_score)
    
for i in range(Team2_bat.shape[0]):
    u = np.sqrt(Team2_bat.iloc[i]['Matches']/Team2_bat.iloc[i]["Innings"])
    v = 20*Team2_bat.iloc[i]["200"]+10*Team2_bat.iloc[i]["100"]+5*Team2_bat.iloc[i]["50"]
    w = 0.3 * v + 0.7 * Team2_bat.iloc[i]["Avg"]
    y = Team2_bat.iloc[i]["SR"]
#     x = 0.2*(Team2_bat.iloc[i]["Innings"]/Team2_bat.iloc[i]["4s"])  + 0.7*(Team2_bat.iloc[i]["Innings"]/Team2_bat.iloc[i]["6s"])
#     if np.isinf(x):
#         career_score = u*w*y
#     else:
#         career_score = u*w*y*x
    career_score = u*w*y
    batting_scores.append(career_score)

In [43]:
m = max(batting_scores)
for i in range(len(batting_scores)):
    batting_scores[i] = batting_scores[i]/m

In [44]:
bowling_scores = []
for i in range(Team1_bowl.shape[0]):
    u = np.sqrt(Team1_bowl.iloc[i]["Innings"]/Team1_bowl.iloc[i]["Matches"])
    v = 10*Team1_bowl.iloc[i]["5W"]+Team1_bowl.iloc[i]["Wickets"]
    w = Team1_bowl.iloc[i]["Avg"] * Team1_bowl.iloc[i]["Econ"] * Team1_bowl.iloc[i]["SR"]
    y = Team1_bowl.iloc[i]["Bowls"]/Team1_bowl.iloc[i]["Runs"]
#     z = Team1_bowl.iloc[i]["SR"]
#     if z>0:
#         bowler_score = u*(v/w)*(v/z)+y
#     else:
#         bowler_score = u*v/w+y
    bowler_score = u*v/w+y
    bowling_scores.append(bowler_score)
    
for i in range(Team2_bowl.shape[0]):
    u = np.sqrt(int(Team2_bowl.iloc[i]["Innings"])/Team2_bowl.iloc[i]["Matches"])
    v = 10*Team2_bowl.iloc[i]["5W"]+Team2_bowl.iloc[i]["Wickets"]
    w = Team2_bowl.iloc[i]["Avg"] * Team2_bowl.iloc[i]["Econ"] * Team2_bowl.iloc[i]["SR"]
    y = Team2_bowl.iloc[i]["Bowls"]/Team2_bowl.iloc[i]["Runs"]
#     z = Team2_bowl.iloc[i]["SR"]
#     if z>0:
#         bowler_score = u*(v/w)*(v/z)+y
#     else:
#         bowler_score = u*v/w+y
    bowler_score = u*v/w+y
    bowling_scores.append(bowler_score)

C:\Users\mubashar.nazar\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in longlong_scalars

C:\Users\mubashar.nazar\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in double_scalars
  if sys.path[0] == '':
C:\Users\mubashar.nazar\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in longlong_scalars
C:\Users\mubashar.nazar\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:25: RuntimeWarning: invalid value encountered in double_scalars

In [45]:
m = np.nanmax(bowling_scores)
for i in range(len(bowling_scores)):
    bowling_scores[i] = bowling_scores[i]/m

In [46]:
batting_scores = np.array(batting_scores)
bowling_scores = np.array(bowling_scores)

In [47]:
bowling_scores[np.isnan(bowling_scores)] = 0
batting_scores[np.isnan(batting_scores)] = 0

In [48]:
Team1_batting = np.sum(batting_scores[:15])
Team1_bowl = np.sum(bowling_scores[:15])
Team2_batting = np.sum(batting_scores[15:])
Team2_bowl = np.sum(bowling_scores[15:])

In [49]:
print (Team1_batting)
print (Team1_bowl)
print (Team2_batting)
print (Team2_bowl)

6.511319870914914
7.8702239840862545
3.515389334393345
8.171892443583207

In [50]:
Team1_batting/Team2_bowl - Team2_batting/Team1_bowl

0.3501250712662219